blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://discord.gg/pmpVeAEsxz
    about: If you neeed any assistance, or just want to hang around, feel free to join my support server.